# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "common/src/schema.rs"
custom_type_derives = ["Debug", "Clone"]

[migrations_directory]
dir = "common/migrations"
